# -*- coding: utf-8 -*-
"""K-Means library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mS52QP7i8h8PgbhhlYB8IBHz5_RKu5Nq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

data = pd.read_excel("dataset.xlsx",usecols=[1,2]) # read data from excel

plt.scatter(data.x, data.y, s = 20, c = "c", marker = "o", alpha = 1)
plt.show()

data_x = data.iloc[:, 0:2]
array_x = np.array(data_x)
print(array_x)

scaler = MinMaxScaler ()
scaled_x = scaler.fit_transform(array_x)
scaled_x

kmeans = KMeans(n_clusters = 3, random_state=123)
kmeans.fit(scaled_x)
print (kmeans.cluster_centers_)

data["kluster"] = kmeans.labels_

output = plt.scatter(scaled_x[:,0], scaled_x[:,1], s = 100, c = data.kluster, marker = "o", alpha = 1,)

centers = kmeans.cluster_centers_
plt.scatter(centers[:,0], centers[:,1], c='red', s=100, alpha=1, marker="o")

plt.title("K-Means Clustering")
plt.colorbar(output)
plt.savefig("final using library.png")
plt.show()


